#!/bin/sh
### BEGIN INIT INFO
# Provides:          langflow
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Langflow server
# Description:       Langflow server running in background
### END INIT INFO

# Change these to match your installation
DIR=/workspace
DAEMON=langflow
DAEMON_NAME=langflow

# Allow dynamic GPU selection
export CUDA_VISIBLE_DEVICES=all
# Enable PyTorch to select least used GPU dynamically
export CUDA_DEVICE_ORDER=PCI_BUS_ID

# Add any command line options for your daemon here
DAEMON_OPTS="run --host 127.0.0.1 --port 7860 --env-file /etc/environment"

# This next line determines what user the script runs as
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon with dynamic GPU selection"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec env CUDA_VISIBLE_DEVICES=all CUDA_DEVICE_ORDER=PCI_BUS_ID $DAEMON $DAEMON_OPTS > /workspace/logs/langflow.log 2>&1"
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
