server: flux
name: Image to Image (Flux)
params:
  main:
    - name: prompt
      type: string
    - name: image
      type: media
      media_type: image
    - name: steps
      type: number
      min: 5
      max: 30
      step: 1
    - name: denoising
      type: number
      min: 0
      max: 1
      step: .01
  advanced:
