server: flux
name: Text to Image (Flux)
params:
  main:
    - name: Prompt
      id: prompt
      type: textarea
    - name: Aspect Ratio
      id: aspect_ratio
      conf_file: aspect_ratio.yaml
    - name: Steps
      id: steps
      type: number
      min: 1
      max: 60
      step: 20
  advanced:
