x-base-service: &base-service
  env_file:
    - .env.local
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
    args:
      FORCE_FRESH_CLONE: ${FORCE_FRESH_CLONE:-false}
  ports:
    - "3188:3188"
    - "3189:3189"
    - "3190:3190"
    - "3191:3191"
    - "3192:3192"
    - "3193:3193"
    - "3194:3194"
    - "3195:3195"
  restart: unless-stopped
  platform: linux/amd64 

services:
  comfyui:
    <<: *base-service
    container_name: comfy
    image: emprops/comfy:latest
    environment:
      - COMFY_REPO_URL=https://github.com/comfyanonymous/ComfyUI.git
    build:
      args:
        COMFY_REPO_URL: https://github.com/comfyanonymous/ComfyUI.git

  comfyui-fork:
    <<: *base-service
    container_name: comfy-fork
    image: emprops/comfy-fork:latest
    environment:
      - COMFY_REPO_URL=https://github.com/stakeordie/ComfyUI.git
    build:
      args:
        COMFY_REPO_URL: https://github.com/stakeordie/ComfyUI.git

  comfyui-fork-devel:
    <<: *base-service
    container_name: comfy-fork-devel
    image: emprops/comfy-fork-devel:latest
    environment:
      - COMFY_REPO_URL=https://github.com/stakeordie/ComfyUI.git
    build:
      args:
        COMFY_REPO_URL: https://github.com/stakeordie/ComfyUI.git