x-base-service: &base-service
  env_file:
    - .env.local
  ports:
    - "8188:8188"
    - "8189:8189"
    - "8190:8190"
    - "8191:8191"
    - "8192:8192"
    - "8193:8193"
    - "8194:8194"
    - "8195:8195"
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
  environment:
      - PATH=/usr/local/bin:$PATH  # Ensure /usr/local/bin is in the PATH
  restart: unless-stopped
  platform: linux/amd64
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]

services:
  comfyui-video:
    <<: *base-service
    image: emprops/comfy-video:v6
    build:
      args:
        - CONFIG_TYPE=video
    volumes:
      - ./config/video:/workspace/config

  comfyui-flux:
    <<: *base-service
    image: emprops/comfy-flux:latest
    build:
      args:
        - CONFIG_TYPE=flux
    volumes:
      - ./config/flux:/workspace/config

  comfyui-basic:
    <<: *base-service
    image: emprops/comfy-basic:v6
    build:
      args:
        - CONFIG_TYPE=basic
    volumes:
      - ./config/basic:/workspace/config

  comfyui-tester:
    <<: *base-service
    image: emprops/comfy-tester:v1
    build:
      args:
        - CONFIG_TYPE=tester
    volumes:
      - ./config/tester:/workspace/config