x-base-service: &base-service
  env_file:
    - .env.local
  ports:
    - "3188:3188"
    - "3189:3189"
    - "3190:3190"
    - "3191:3191"
    - "3192:3192"
    - "3193:3193"
    - "3194:3194"
    - "3195:3195"
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
  restart: unless-stopped
  platform: linux/amd64
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]

services:
  comfyui-video:
    <<: *base-service
    image: emprops/comfy-video:v6
    build:
      args:
        - CONFIG_TYPE=video
    volumes:
      - ./config/video:/workspace/config

  comfyui-flux:
    <<: *base-service
    image: emprops/comfy-flux:latest
    build:
      args:
        - CONFIG_TYPE=flux
    volumes:
      - ./config/flux:/workspace/config

  comfyui-basic:
    <<: *base-service
    image: emprops/comfy-basic:v6
    build:
      args:
        - CONFIG_TYPE=basic
    volumes:
      - ./config/basic:/workspace/config

  comfyui-tester:
    <<: *base-service
    image: emprops/comfy-tester:v1
    build:
      args:
        - CONFIG_TYPE=tester
    volumes:
      - ./config/tester:/workspace/config