x-base-service: &base-service
  env_file:
    - .env.local
  ports:
    - "3188:3188"
    - "3189:3189"
    - "3190:3190"
    - "3191:3191"
    - "3192:3192"
    - "3193:3193"
    - "3194:3194"
    - "3195:3195"
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
    args:
      CACHEBUST: ${CACHEBUST:-1}  # Add this line
  restart: unless-stopped
  platform: linux/amd64 
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]

services:
  comfyui:
    <<: *base-service
    container_name: comfy
    image: emprops/comfy:latest