#!/bin/bash
### BEGIN INIT INFO
# Provides:          comfyui
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ComfyUI
### END INIT INFO

# Path to your virtual environment
VENV_PATH=/comfyui-launcher/ComfyUI/venv

# Path to your Python script
SCRIPT_PATH=/comfyui-launcher/ComfyUI/main.py

PYTHON_PATH=/comfyui-launcher/ComfyUI/venv/bin/python

# Log Path
LOG_PATH=/tmp/comfyui_debug.log

case "$1" in
    start)
        echo "Starting ComfyUI"
        echo "Starting ComfyUI at $(date)" >> $LOG_PATH
        $PYTHON_PATH $SCRIPT_PATH --listen 0.0.0.0 >> $LOG_PATH 2>&1 &
        COMFYUI_PID=$!
        echo "ComfyUI started with PID $COMFYUI_PID" >> $LOG_PATH
        echo "ComfyUI started with PID $COMFYUI_PID"  # Output the PID for debugging
        ;;
    stop)
        echo "Stopping ComfyUI"
        pkill -f "/comfyui-launcher/ComfyUI/main.py"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0