# Docker Compose configuration for EmProps Component Library
version: '3.8'

# Base service configuration
x-base-service: &base-service
  env_file:
    - .env.local
  build:
    context: .
    dockerfile: Dockerfile
    args:
      FORCE_FRESH_CLONE: ${FORCE_FRESH_CLONE:-false}
  ports:
    - "3188:3188"
    - "3189:3189"
    - "3190:3190"
    - "3191:3191"
    - "3192:3192"
    - "3193:3193"
    - "3194:3194"
    - "3195:3195"
  restart: unless-stopped

services:
  # ComfyUI services
  comfyui-fork-devel:
    <<: *base-service
    container_name: comfy-fork-devel
    image: emprops/comfy-fork-devel:latest
    environment:
      - COMFY_REPO_URL=https://github.com/stakeordie/ComfyUI.git
    build:
      args:
        COMFY_REPO_URL: https://github.com/stakeordie/ComfyUI.git