server: basic
name: Text to Image
params:
  main:
    - name: Model
      id: model
      conf_file: all_models.yaml
    - name: Prompt
      id: prompt
      type: textarea
    - name: Negative Prompt
      id: negative_prompt
      type: textarea
    - name: Aspect Ratio
      id: aspect_ratio
      conf_file: aspect_ratio.yaml
    - name: Steps
      id: steps
      type: number
      min: 1
      max: 60
      step: 20
  advanced:
    - name: Sampler
      id: sampler
      default: Euler a
      conf_file: samplers.yaml
    - name: Scheduler
      id: scheduler
      default: Karras
      conf_file: schedulers.yaml
    - name: Guidance (CFG)
      id: cfg
      type: number
      default: 7
      min: 0
      max: 50
      steps: .01